version: '3.8'
services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - oauth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  oauth_db_data: